### ISSUE TITLE
Error Deploying Confluent Kafka Platform with RBAC

### ISSUE THREAD

**Issue by tariqsiddiqui** [confluentinc/operator-earlyaccess#70]
I tried to depoy confluent kafka platform with rbac and got this error.
kubectl apply -f $TUTORIAL_HOME/confluent-platform-rbac-secure.yaml
zookeeper.platform.confluent.io/zookeeper created
error: error validating "/Users/tariq/git/operator-earlyaccess/cp-rbac-deploy/confluent-platform-rbac-secure.yaml": error validating data: [ValidationError(Kafka.spec.services.mds): unknown field "ldap" in io.confluent.platform.v1beta1.Kafka.spec.services.mds, ValidationError(Kafka.spec.services.mds): missing required field "provider" in io.confluent.platform.v1beta1.Kafka.spec.services.mds, ValidationError(Kafka.spec.services): unknown field "restProxy" in io.confluent.platform.v1beta1.Kafka.spec.services]; if you choose to ignore these errors, turn validation off with --validate=false

I was able to deploy a simple confluent platform without any problem:
kubectl apply -f $TUTORIAL_HOME/confluent-platform.yaml

**Comment by mccullya** [comment]
I'm having the same issue with the restProxy.  I've Managed to get past the ldap issue by changing the yaml to:

```
  services:
    mds:
      provider:
        ldap:
          address: ldap://ldap.confluent.svc.cluster.local:389
          authentication:
            simple:
              secretRef: kafka-secret
            type: simple
          configurations:
            groupMemberAttribute: member
            groupMemberAttributePattern: cn=(.*?),.*,dc=foo,dc=bar
            groupNameAttribute: cn
            groupObjectClass: groupOfNames
            groupSearchBase: ou=groups,dc=foo,dc=com
            userMemberOfAttributePattern: cn=(.*),ou=groups,dc=foo,dc=bar
            userNameAttribute: cn
            userObjectClass: '*'
            userSearchBase: dc=foo,dc=bar
        type: ldap
```

But looking at the kafka CRD, it seems that restProxy has been removed from the services section (?) as i only see mds there now.  The only reference to restproxy the crd, is an option in 'dependencies'.

Is there a different method to get restProxy up and running with the latest version of confluent operator?
